name: Build recovery (TWRP, SHRP, PBRP)
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y wget zip curl git

      - name: Remove Previous Packages and Setup Repo
        run: |
          wget -qO - https://github.com/SA-17/Recovery_builder/raw/main/scripts/cleanup.sh | bash
          curl --create-dirs -L -o /usr/local/bin/repo https://storage.googleapis.com/git-repo-downloads/repo
          chmod a+rx /usr/local/bin/repo

      - name: Configure Source
        run: |
          source config.sh
          mkdir -p work || { echo "Error: Failed to create work directory"; exit 1; }
          cd work || { echo "Error: Failed to change directory to work"; exit 1; }
          repo init -u $MANIFEST -b $BRANCH --depth=1 || { echo "Error: Failed to initialize repo"; exit 1; }
          repo sync -c -j$(nproc) --force-sync --no-clone-bundle --no-tags || { echo "Error: Failed to sync repo"; exit 1; }
          git clone $DT_LINK -b $DT_BRANCH device/$VENDOR/$DEVICE || { echo "Error: Failed to clone device tree"; exit 1; }

      - name: Build Recovery
        run: |
          source config.sh
          cd work || { echo "Error: Failed to change directory to work"; exit 1; }
          . build/envsetup.sh
          lunch twrp_a24-eng
          export ALLOW_MISSING_DEPENDENCIES=true
          mka recoveryimage -j2 || { echo "Error: Failed to build the target"; exit 1; }

      - name: Compress Recovery Image
        run: |
          cd work || { echo "Error: Failed to change directory to work"; exit 1; }
          zip -r recovery.zip recovery.img || { echo "Error: Failed to compress recovery image"; exit 1; }

      - name: Release Recovery
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.run_id }}
          name: Recovery Image
          files: work/recovery.zip
